#ifndef INTERFACE_H
#define INTERFACE_H

const char HTML_BODY[] =
    "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Estação Meteorológica</title>"
    "<style>canvas{background:#fff;border:1px solid #ccc;} h1{text-align:center;}</style>"
    "<script>"
    "let historico = [];"
    "let paginaAtual = null;"
    "let camposPreenchidos = false;"
    "function atualizar() {"
    "  fetch('/estado').then(res => res.json()).then(data => {"
    "    document.getElementById('nome').innerText = data.nome;"
    "    document.getElementById('valor').innerText = data.valor.toFixed(2) + ' ' + (data.unidade || '');"
    "    historico = data.historico;"
    "    desenharGrafico();"
    "    if (paginaAtual !== data.pagina || !camposPreenchidos) {"
    "      document.getElementById('lim_min').value = data.lim_min;"
    "      document.getElementById('lim_max').value = data.lim_max;"
    "      document.getElementById('offset').value = data.offset;"
    "      paginaAtual = data.pagina;"
    "      camposPreenchidos = true;"
    "    }"
    "  });"
    "}"
    "function desenharGrafico() {"
    "  let c = document.getElementById('grafico');"
    "  let ctx = c.getContext('2d');"
    "  ctx.clearRect(0,0,c.width,c.height);"
    "  if(historico.length<2) return;"
    "  let min = Math.min(...historico), max = Math.max(...historico);"
    "  if(min==max) {min-=1;max+=1;}"
    "  let w = c.width, h = c.height, n = historico.length;"
    "  ctx.beginPath();"
    "  for(let i=0;i<n;i++){"
    "    let x = i*(w/(n-1));"
    "    let y = h-(h*(historico[i]-min)/(max-min));"
    "    if(i==0) ctx.moveTo(x,y); else ctx.lineTo(x,y);"
    "  }"
    "  ctx.strokeStyle='#336699';ctx.lineWidth=2;ctx.stroke();"
    "}"
    "function enviarConfig() {"
    "  let lim_min = parseFloat(document.getElementById('lim_min').value);"
    "  let lim_max = parseFloat(document.getElementById('lim_max').value);"
    "  let offset = parseFloat(document.getElementById('offset').value);"
    "  let pagina = paginaAtual;"
    "  fetch('/config', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pagina,lim_min,lim_max,offset})})"
    "    .then(()=>{camposPreenchidos=false; setTimeout(atualizar,300);});"
    "  return false;"
    "}"
    "function mudarPagina() {"
    "  fetch('/pagina', {method:'POST'})"
    "    .then(()=>{setTimeout(atualizar,300);});"
    "}"
    "setInterval(atualizar, 1000);"
    "window.onload=atualizar;"
    "</script></head><body>"
    "<h1 id='titulo'>Estação Meteorológica</h1>"
    "<div style='margin-top:30px; text-align:center;'>"
    "  <h2 id='nome'>--</h2>"
    "  <div style='font-size:2.5em; margin:20px 0;' id='valor'>--</div>"
    "  <canvas id='grafico' width='320' height='100'></canvas>"
    "  <form onsubmit='return enviarConfig();' style='margin:20px auto;max-width:320px;'>"
    "    <label>Limite Mín: <input id='lim_min' type='number' step='any'></label><br>"
    "    <label>Limite Máx: <input id='lim_max' type='number' step='any'></label><br>"
    "    <label>Offset: <input id='offset' type='number' step='any'></label><br>"
    "    <button type='submit'>Salvar</button>"
    "  </form>"
    "  <button onclick='mudarPagina();' style='margin-top:10px;'>Mudar Página</button>"
    "  <p style='font-size:1em; color:#888;'>Pressione o botão A para alternar a leitura exibida</p>"
    "</div>"
    "<hr style='margin-top: 20px;'>"
    "<p style='font-size: 15px; color: #336699; font-style: italic; max-width: 90%; margin: 10px auto;'>"
    "</p>"
    "</body></html>";


#endif